package com.homektv.domain;

import jakarta.persistence.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.time.OffsetDateTime;

/**
 * 轻量点歌人标识（非账号体系），对应 users 表（详设§10）。
 *
 * Lightweight singer identifier (not an account system), corresponding to the users table (detailed design §10).
 */
@Entity
@Table(name = "users")
public class AppUser {

    /** 主键，自增。 Primary key, auto-increment. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** 客户端标识令牌，唯一标识每个点歌客户端。 Client token, uniquely identifying each karaoke client. */
    @Column(name = "client_token", nullable = false, unique = true)
    private String clientToken;

    /** 点歌人昵称。 Singer nickname. */
    @Column(nullable = false)
    private String nickname;

    /** 创建时间，由数据库自动生成。 Creation timestamp, auto-generated by the database. */
    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    // ---- getters / setters ----

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getClientToken() { return clientToken; }
    public void setClientToken(String clientToken) { this.clientToken = clientToken; }
    public String getNickname() { return nickname; }
    public void setNickname(String nickname) { this.nickname = nickname; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
}
